### ISSUE TITLE
new design elements too big

### ISSUE THREAD

**Issue by hexsprite** [meteor-velocity/html-reporter#42]
As much as I love the design of the velocity reporter (looks really slick!) --  I am concerned that the test results themselves are way down below the fold.  I would love to see the summary of the results at the top be like 30% smaller or something.  Anyone else feel the same way?

Also there is information that is duplicated, namely the number of tests passing and the time it took.  Again this takes away from the actual test results which I care about.

**Comment by samhatoum** [comment]
"fixed"
