### ISSUE TITLE
Aggregate timing not accurate

### ISSUE THREAD

**Issue by samhatoum** [meteor-velocity/html-reporter#50]
The current total time adds up all the times of the tests. It's showing the sum of all tests, but not the start/finish of the total test run.

This is inaccurate as the framework may be doing things between tests, such as starting/stopping services. This all adds up to the total time.

**Comment by Sanjo** [comment]
Velocity checks currently allow a String as timestamp. We need to convert it into a date.

**Comment by Sanjo** [comment]
I think we should move the totalTime function to velocity:core, so other reporters can use it.

**Comment by queso** [comment]
+1
