### ISSUE TITLE
Nightwatch tests aren't showing up in sequential order.

### ISSUE THREAD

**Issue by awatson1978** [meteor-velocity/html-reporter#59]
Nightwatch test files are sequential and depend on being run in chronological order.  In the screenshot below, the very last line ``Element <#customersTable> was visible after 24 milliseconds.`` was actually the first test to be run; but is showing up last on the list.  There are times when the tests get completely out of order.  Impossible to use for debugging purposes if the tests aren't in sequential order.

Would like to maybe add sorting to [the reports() function in client-reporter.js](https://github.com/meteor-velocity/html-reporter/blob/devel/lib/client-report.js#L141-146)

![screen shot 2015-01-31 at 3 33 51 pm](https://cloud.githubusercontent.com/assets/675910/5989733/97ace0f6-a95e-11e4-85d4-d08cc99988bd.png)

**Comment by queso** [comment]
I think the important question here is: What is minimongo table? That looks nice :)

**Comment by awatson1978** [comment]
:)
A lot of the work I do is sort of dry and boring, mostly CRUDL stuff.  Minimongo table was a scratchpad for a pure table implementation in Meteor, using just Blaze and Bootstrap.  No jquery datatables, or anything.  It's been sitting around for a year or more.

With Meteor 1.0 come out a few months ago, I've been slowly going through the cookbook, upgrading all the examples to 1.0 and adding acceptance tests (and starting with MiniMongoTable, unit tests also).  

Once all the tests are in place, I'm going to try to refactor it and extract a table webcomponent and Table API.  I'm getting pretty close....

**Comment by Sanjo** [comment]
Would sorting ascending by timestamp (the time when the test result was reported) solve the problem?

**Comment by awatson1978** [comment]
Yeah, that's all that's needed, I think.

**Comment by Sanjo** [comment]
:+1: for this change

**Comment by awatson1978** [comment]
I'll put the pull-request together....  just logged the ticket so as to go through the process.

**Comment by samhatoum** [comment]
Nightwatch withdrawn by author. Closing issue
