### ISSUE TITLE
Total time helper invalid date err

### ISSUE THREAD

**Issue by dbernhard** [meteor-velocity/html-reporter#61]
My client side tests (jasmine) are throwing an error that prevents total time from showing in the reporter. This is a fairly minor issue so far as the tests themselves are concerned, but it does clog up my console with error logs that make it hard to debug the rest of the code.

The error occurs in `client-report.js` at lines 163 and 166. The problem is that `result.timestamp` isn't a date , so the `.getTime()` method is undefined. Instead it's a string that looks something like this `"14:35:02 GMT-0500 (EST)"`.

I would post this as a PR but am not sure how you want to handle this. On the one hand, we could set `result.timestamp` to be a valid date when it gets set. On the other hand, we can just convert it to one in the `totalTime` helper.

Please let me know how you'd like to handle this and I'd be happy to contribute the modification.

db

**Comment by Sanjo** [comment]
The latest version of sanjo:jasmine (0.12.3) reportes Date objects instead of timestamps. So this issue should be fixed in the scope of sanjo:jasmine.

I've also just done https://github.com/meteor-velocity/velocity/commit/9beaad3d73bb94aa13367f1cd4212d42a638c410 for velocity:core.
