### ISSUE TITLE
How to remove top right triangle?

### ISSUE THREAD

**Issue by mediatainment** [meteor-velocity/html-reporter#63]
Is there another way disabling the top right triangle without removing the whole package again and again?

My ENV looks like this:

```
DEBUG=0
VELOCITY=0
VELOCITY_DEBUG=0
VELOCITY_DEBUG_MIRROR=0
JASMINE=0
JASMINE_DEBUG=0
JASMINE_SERVER_INTEGRATION=0
JASMINE_SERVER_UNIT=0
JASMINE_CLIENT_INTEGRATION=0
JASMINE_CLIENT_UNIT=0
JASMINE_DEBUG=0
```

With this setting It still appears....

Any suggestion?

Thank you very much

**Comment by Sanjo** [comment]
As long as you just use sanjo:jasmine and you don't want to use the velocity:html-reporter and the velocity:console-reporter instead for example, you can just `meteor remove velocity:html-reporter`.

You can also modify the CSS. See https://github.com/meteor-velocity/html-reporter/issues/54#issuecomment-73871623.

**Comment by Sanjo** [comment]
The velocity:html-reporter is automatically removed when you build or deploy you app for production.

**Comment by xumx** [comment]
Maybe we can use a hotkey to activate the triangle. Something like https://github.com/msavin/Mongol

right now it is intrusive and blocks a important section of the screen. (common area for user profile/menu button)

**Comment by Sanjo** [comment]
@xumx I think a hotkey for toggling the triangle is a good addition. A pull-request for this functionality would be accepted.

**Comment by guilhermedecampo** [comment]
1+ for this functionality ! 
Developing mobile with html-reporter can be boring.

I added a main.js in client's folder with this:
```
_.defer(function() {
  $('#velocity-status-widget').hide();
});
```

**Comment by samhatoum** [comment]
this is now fixes. ctrl-v hides the reporter and you can now configure the position in the settings file.

**Comment by guilhermedecampo** [comment]
awesome!
