### ISSUE TITLE
ReferenceError: SYMBOL_ITERATOR is not defined

### ISSUE THREAD

**Issue by myknbani** [meteor-velocity/html-reporter#87]
I got this error when I upgraded html-reporter to 0.8.2, it works previously on 0.7.3.  This upgrade pulls `grigio:babel`, and produces this stacktrace:

    ReferenceError: SYMBOL_ITERATOR is not defined
        W20150813-15:10:26.838(8)? (STDERR)     at checkIter (packages/grigio:babel/lib/core-js-no-number.js:1060:1)
        W20150813-15:10:26.839(8)? (STDERR)     at getCollection (packages/grigio:babel/lib/core-js-no-number.js:1089:1)
        W20150813-15:10:26.839(8)? (STDERR)     at Object../$ (packages/grigio:babel/lib/core-js-no-number.js:1233:1)
        W20150813-15:10:26.839(8)? (STDERR)     at s (packages/grigio:babel/lib/core-js-no-number.js:10:1)
        W20150813-15:10:26.839(8)? (STDERR)     at packages/grigio:babel/lib/core-js-no-number.js:10:1
        W20150813-15:10:26.839(8)? (STDERR)     at Object../src/es5 (packages/grigio:babel/lib/core-js-no-number.js:25:1)
        W20150813-15:10:26.839(8)? (STDERR)     at s (packages/grigio:babel/lib/core-js-no-number.js:10:1)
        W20150813-15:10:26.840(8)? (STDERR)     at e (packages/grigio:babel/lib/core-js-no-number.js:10:1)
        W20150813-15:10:26.840(8)? (STDERR)     at hasOwn (packages/grigio:babel/lib/core-js-no-number.js:10:1)
        W20150813-15:10:26.840(8)? (STDERR)     at hasOwn (packages/grigio:babel/lib/core-js-no-number.js:2233:1)

Reverting to the old versions work.

Also, I'm not sure if this would help, but I'm also using `pbastowski:angular-babel` for its `ng-annotate` magic.

velocity:chokidar@1.0.3_1
velocity:console-reporter@0.1.3
velocity:core@0.9.3
velocity:html-reporter@0.8.2
velocity:meteor-internals@1.1.0_7
velocity:shim@0.1.0
velocity:source-map-support@0.3.2_1
webapp@1.2.0
webapp-hashing@1.0.3
xolvio:cucumber@0.13.8

**Comment by samhatoum** [comment]
Strange. Do you think you could replicate this in a repo?

**Comment by myknbani** [comment]
Yes, I'll try to reproduce using a fresh project.

**Comment by myknbani** [comment]
Load order seems to matter.  As seen in the stacktrace above, it is the `grigio:babel` package producing the error, now it is `pbastowski:angular-babel`.

Here is the repo:  https://github.com/myknbani/angular-babel-bug

Steps to reproduce:

1. Add the packages `meteor add pbastowski:angular-babel xolvio:cucumber velocity:html-reporter`
2. run the app, watch it crash
3. Remove `pbastowski:angular-babel`, and the app runs.

**Comment by myknbani** [comment]
Seems like the two babel packages are clashing.  Anyway as long as the additions in the 0.8.2 version are purely aesthetics, I don't mind using an older version.

**Comment by samhatoum** [comment]
They are purely aesthetic for now, though you also have links to the mirrors now plus mirror state. Nothing you can't live without.

**Comment by myknbani** [comment]
I think we can just close this.  There's an official `ecmascript` package anyway.  I'll just resort to manually annotating my angular files.

Thanks for the quick feedback! :D
