### ISSUE TITLE
hiding html-reporter doesn't work

### ISSUE THREAD

**Issue by markusgattol** [meteor-velocity/html-reporter#89]
after `meteor add velocity:html-reporter`, all I see is the reporter html page with no way to 'see' my actual apps html anymore. `Ctrl + v` doesn't seem to work either? any ideas?

Screenshot so to show the problem I am facing. Probably super-ridiculous but still... ![screenshot_1440750745](https://cloud.githubusercontent.com/assets/649821/9542339/22142af0-4d70-11e5-9689-9cd7c67983d1.png) I am using webstorm on the right, chromium on the left, window manager is awesome on Debian.

After removing it again, apps html is back as before
![screenshot_1440751111](https://cloud.githubusercontent.com/assets/649821/9542439/0c047110-4d71-11e5-91bb-9bb745e1d72e.png)

**Comment by AdamBrodzinski** [comment]
+1, I had the same issue when upgrading to the 1.2 RC preview. Not sure if it's related. The first time I had checkmarks without text and the latest time no checkmarks and no text.

**Comment by Sanjo** [comment]
Fixed with 0.9.0
