### ISSUE TITLE
Move Control buttons above framework reports

### ISSUE THREAD

**Issue by rjsmith** [meteor-velocity/html-reporter#92]
Please consider moving the velocity control buttons ('Show passed tests' etc) back above the framework reports.  If I am watching the framework reports reactively build up, the buttons get pushed below the viewport, so I have to scroll down and hunt for the fast - disappearing buttons to be able to click one of them (e.g. turn off 'Show passed tests').  This is a PITA.

There was a commit that moved the control buttons below the framework reports here: https://github.com/meteor-velocity/html-reporter/commit/8be59f0ebe3b4a7455706b7b63534d83e1b5e702

I'm happy to do a PR but I wonder if this was a deliberate design choice?  If so, interested to hear the rationale behind it  :-)

**Comment by Sanjo** [comment]
Can you do a PR please. I will merge and release it.

**Comment by rjsmith** [comment]
Hi @Sanjo OK .. hope to get to this tomorrow evening (UK time)
